### ISSUE TITLE
internal server error for pdf generation although pdf is generated.

### ISSUE THREAD

**Issue by colorblast** [JonW27/labob#17]
Tells me to relax even though it is crashing.
![screen shot 2016-06-04 at 2 39 05 pm](https://cloud.githubusercontent.com/assets/8844453/15801433/5d21977a-2a62-11e6-8b77-b4d407b2a900.jpg)

**Comment by brian-i** [comment]
Does pdflatex crash with all output files?
This is very unexpected behavior, because my local copy works fine (my Mac works OK).
This may be a permissions issue, so SSH into marge, navigate to the labob directory, and run the following commands, in successive order:
`touch output.tex`
`touch output.synctex.gz`
`touch output.pdf`
`touch output.log`
`touch output.aux`
`chmod 777 output.tex`
`chmod 777 output.synctex.gz`
`chmod 777 output.pdf`
`chmod 777 output.log`
`chmod 777 output.aux`
**WAIT:** First delete all `output` files _before_ running these commands.

**Comment by colorblast** [comment]
![screen shot 2016-06-04 at 5 29 45 pm](https://cloud.githubusercontent.com/assets/8844453/15802240/f2c3483e-2a79-11e6-9a48-e8199012452d.jpg)

EDIT: DISREGARD THIS COMMENT.

**Comment by colorblast** [comment]
PDF generation for standard works, but it does not redirect and it instead leads to an internal server error.

**Comment by brian-i** [comment]
I have a fix, yet please see Issue #21 regarding how I can commit it if we have been working separately.

**Comment by brian-i** [comment]
Whoops! I stopped getting ISE, but the PDF never changes!

**Comment by brian-i** [comment]
Now the PDF generation appears to work OK; please see Issue #21.
